# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 571)
        MainWindow.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textMain = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textMain.sizePolicy().hasHeightForWidth())
        self.textMain.setSizePolicy(sizePolicy)
        self.textMain.setObjectName("textMain")
        self.horizontalLayout.addWidget(self.textMain)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSearch.sizePolicy().hasHeightForWidth())
        self.lineSearch.setSizePolicy(sizePolicy)
        self.lineSearch.setBaseSize(QtCore.QSize(5, 1))
        self.lineSearch.setAutoFillBackground(False)
        self.lineSearch.setInputMask("")
        self.lineSearch.setText("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setFrame(True)
        self.lineSearch.setReadOnly(False)
        self.lineSearch.setClearButtonEnabled(True)
        self.lineSearch.setObjectName("lineSearch")
        self.horizontalLayout.addWidget(self.lineSearch)
        self.pushSearch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushSearch.sizePolicy().hasHeightForWidth())
        self.pushSearch.setSizePolicy(sizePolicy)
        self.pushSearch.setMinimumSize(QtCore.QSize(0, 0))
        self.pushSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushSearch.setAutoDefault(False)
        self.pushSearch.setDefault(False)
        self.pushSearch.setFlat(False)
        self.pushSearch.setObjectName("pushSearch")
        self.horizontalLayout.addWidget(self.pushSearch)
        self.pushRefresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRefresh.sizePolicy().hasHeightForWidth())
        self.pushRefresh.setSizePolicy(sizePolicy)
        self.pushRefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushRefresh.setAutoFillBackground(False)
        self.pushRefresh.setObjectName("pushRefresh")
        self.horizontalLayout.addWidget(self.pushRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listCity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCity.sizePolicy().hasHeightForWidth())
        self.listCity.setSizePolicy(sizePolicy)
        self.listCity.setStyleSheet("font: 48pt \"Cantarell\";")
        self.listCity.setObjectName("listCity")
        self.verticalLayout.addWidget(self.listCity)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listInfo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listInfo.sizePolicy().hasHeightForWidth())
        self.listInfo.setSizePolicy(sizePolicy)
        self.listInfo.setStyleSheet("font: 36pt \"Cantarell\";")
        self.listInfo.setObjectName("listInfo")
        self.horizontalLayout_5.addWidget(self.listInfo)
        self.listCelsius = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCelsius.sizePolicy().hasHeightForWidth())
        self.listCelsius.setSizePolicy(sizePolicy)
        self.listCelsius.setStyleSheet("font: 36pt \"Cantarell\";")
        self.listCelsius.setObjectName("listCelsius")
        self.horizontalLayout_5.addWidget(self.listCelsius)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listDay_1 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_1.setObjectName("listDay_1")
        self.horizontalLayout_2.addWidget(self.listDay_1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.listDay_2 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_2.setObjectName("listDay_2")
        self.horizontalLayout_2.addWidget(self.listDay_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.listDay_3 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_3.setObjectName("listDay_3")
        self.horizontalLayout_2.addWidget(self.listDay_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.listDay_4 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_4.setObjectName("listDay_4")
        self.horizontalLayout_2.addWidget(self.listDay_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineSearch, self.pushSearch)
        MainWindow.setTabOrder(self.pushSearch, self.pushRefresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textMain.setText(_translate("MainWindow", "TextLabel"))
        self.pushSearch.setText(_translate("MainWindow", "Найти"))
        self.pushSearch.setShortcut(_translate("MainWindow", "Return"))
        self.pushRefresh.setText(_translate("MainWindow", "Обновить"))
        self.listCity.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.listInfo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.listCelsius.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.listDay_1.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_2.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_3.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_4.setText(_translate("MainWindow", "TextLabel"))
