# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 727)
        MainWindow.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textMain = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textMain.sizePolicy().hasHeightForWidth())
        self.textMain.setSizePolicy(sizePolicy)
        self.textMain.setObjectName("textMain")
        self.horizontalLayout.addWidget(self.textMain)
        self.listCity = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCity.sizePolicy().hasHeightForWidth())
        self.listCity.setSizePolicy(sizePolicy)
        self.listCity.setStyleSheet("font: 48pt \"Cantarell\";")
        self.listCity.setObjectName("listCity")
        self.horizontalLayout.addWidget(self.listCity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineSearch = QtWidgets.QLineEdit(self.centralwidget)
        self.lineSearch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSearch.sizePolicy().hasHeightForWidth())
        self.lineSearch.setSizePolicy(sizePolicy)
        self.lineSearch.setBaseSize(QtCore.QSize(5, 1))
        self.lineSearch.setAutoFillBackground(False)
        self.lineSearch.setInputMask("")
        self.lineSearch.setText("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setFrame(True)
        self.lineSearch.setReadOnly(False)
        self.lineSearch.setClearButtonEnabled(True)
        self.lineSearch.setObjectName("lineSearch")
        self.horizontalLayout.addWidget(self.lineSearch)
        self.pushSearch = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushSearch.sizePolicy().hasHeightForWidth())
        self.pushSearch.setSizePolicy(sizePolicy)
        self.pushSearch.setMinimumSize(QtCore.QSize(0, 0))
        self.pushSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushSearch.setAutoDefault(False)
        self.pushSearch.setDefault(False)
        self.pushSearch.setFlat(False)
        self.pushSearch.setObjectName("pushSearch")
        self.horizontalLayout.addWidget(self.pushSearch)
        self.pushRefresh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushRefresh.sizePolicy().hasHeightForWidth())
        self.pushRefresh.setSizePolicy(sizePolicy)
        self.pushRefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushRefresh.setAutoFillBackground(False)
        self.pushRefresh.setObjectName("pushRefresh")
        self.horizontalLayout.addWidget(self.pushRefresh)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.time_6_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_6_inf.sizePolicy().hasHeightForWidth())
        self.time_6_inf.setSizePolicy(sizePolicy)
        self.time_6_inf.setObjectName("time_6_inf")
        self.gridLayout.addWidget(self.time_6_inf, 2, 11, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 3, 4, 1, 1)
        self.line_52 = QtWidgets.QFrame(self.centralwidget)
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.gridLayout.addWidget(self.line_52, 2, 12, 1, 1)
        self.line_49 = QtWidgets.QFrame(self.centralwidget)
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.gridLayout.addWidget(self.line_49, 2, 6, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 0, 14, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 3, 12, 1, 1)
        self.time_7_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_7_inf.sizePolicy().hasHeightForWidth())
        self.time_7_inf.setSizePolicy(sizePolicy)
        self.time_7_inf.setObjectName("time_7_inf")
        self.gridLayout.addWidget(self.time_7_inf, 2, 13, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 0, 6, 1, 1)
        self.line_43 = QtWidgets.QFrame(self.centralwidget)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.gridLayout.addWidget(self.line_43, 1, 9, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 3, 10, 1, 1)
        self.line_44 = QtWidgets.QFrame(self.centralwidget)
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.gridLayout.addWidget(self.line_44, 1, 11, 1, 1)
        self.line_50 = QtWidgets.QFrame(self.centralwidget)
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.gridLayout.addWidget(self.line_50, 2, 8, 1, 1)
        self.icon_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_4.sizePolicy().hasHeightForWidth())
        self.icon_4.setSizePolicy(sizePolicy)
        self.icon_4.setObjectName("icon_4")
        self.gridLayout.addWidget(self.icon_4, 3, 7, 1, 1)
        self.icon_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_3.sizePolicy().hasHeightForWidth())
        self.icon_3.setSizePolicy(sizePolicy)
        self.icon_3.setObjectName("icon_3")
        self.gridLayout.addWidget(self.icon_3, 3, 5, 1, 1)
        self.line_39 = QtWidgets.QFrame(self.centralwidget)
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.gridLayout.addWidget(self.line_39, 1, 1, 1, 1)
        self.time_2_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_2_inf.sizePolicy().hasHeightForWidth())
        self.time_2_inf.setSizePolicy(sizePolicy)
        self.time_2_inf.setObjectName("time_2_inf")
        self.gridLayout.addWidget(self.time_2_inf, 2, 3, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 0, 10, 1, 1)
        self.time_3_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_3_inf.sizePolicy().hasHeightForWidth())
        self.time_3_inf.setSizePolicy(sizePolicy)
        self.time_3_inf.setObjectName("time_3_inf")
        self.gridLayout.addWidget(self.time_3_inf, 2, 5, 1, 1)
        self.time_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_4.sizePolicy().hasHeightForWidth())
        self.time_4.setSizePolicy(sizePolicy)
        self.time_4.setObjectName("time_4")
        self.gridLayout.addWidget(self.time_4, 0, 7, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 8, 1, 1)
        self.time_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_5.sizePolicy().hasHeightForWidth())
        self.time_5.setSizePolicy(sizePolicy)
        self.time_5.setObjectName("time_5")
        self.gridLayout.addWidget(self.time_5, 0, 9, 1, 1)
        self.icon_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_6.sizePolicy().hasHeightForWidth())
        self.icon_6.setSizePolicy(sizePolicy)
        self.icon_6.setObjectName("icon_6")
        self.gridLayout.addWidget(self.icon_6, 3, 11, 1, 1)
        self.line_40 = QtWidgets.QFrame(self.centralwidget)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.gridLayout.addWidget(self.line_40, 1, 3, 1, 1)
        self.icon_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_2.sizePolicy().hasHeightForWidth())
        self.icon_2.setSizePolicy(sizePolicy)
        self.icon_2.setObjectName("icon_2")
        self.gridLayout.addWidget(self.icon_2, 3, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 3, 2, 1, 1)
        self.time_8_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_8_inf.sizePolicy().hasHeightForWidth())
        self.time_8_inf.setSizePolicy(sizePolicy)
        self.time_8_inf.setObjectName("time_8_inf")
        self.gridLayout.addWidget(self.time_8_inf, 2, 15, 1, 1)
        self.time_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_3.sizePolicy().hasHeightForWidth())
        self.time_3.setSizePolicy(sizePolicy)
        self.time_3.setObjectName("time_3")
        self.gridLayout.addWidget(self.time_3, 0, 5, 1, 1)
        self.line_42 = QtWidgets.QFrame(self.centralwidget)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.gridLayout.addWidget(self.line_42, 1, 7, 1, 1)
        self.icon_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_8.sizePolicy().hasHeightForWidth())
        self.icon_8.setSizePolicy(sizePolicy)
        self.icon_8.setObjectName("icon_8")
        self.gridLayout.addWidget(self.icon_8, 3, 15, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 3, 8, 1, 1)
        self.time_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_2.sizePolicy().hasHeightForWidth())
        self.time_2.setSizePolicy(sizePolicy)
        self.time_2.setObjectName("time_2")
        self.gridLayout.addWidget(self.time_2, 0, 3, 1, 1)
        self.time_6 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_6.sizePolicy().hasHeightForWidth())
        self.time_6.setSizePolicy(sizePolicy)
        self.time_6.setObjectName("time_6")
        self.gridLayout.addWidget(self.time_6, 0, 11, 1, 1)
        self.time_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_8.sizePolicy().hasHeightForWidth())
        self.time_8.setSizePolicy(sizePolicy)
        self.time_8.setObjectName("time_8")
        self.gridLayout.addWidget(self.time_8, 0, 15, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 3, 14, 1, 1)
        self.line_48 = QtWidgets.QFrame(self.centralwidget)
        self.line_48.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.gridLayout.addWidget(self.line_48, 2, 4, 1, 1)
        self.line_46 = QtWidgets.QFrame(self.centralwidget)
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.gridLayout.addWidget(self.line_46, 1, 15, 1, 1)
        self.time_1_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_1_inf.sizePolicy().hasHeightForWidth())
        self.time_1_inf.setSizePolicy(sizePolicy)
        self.time_1_inf.setObjectName("time_1_inf")
        self.gridLayout.addWidget(self.time_1_inf, 2, 1, 1, 1)
        self.icon_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_1.sizePolicy().hasHeightForWidth())
        self.icon_1.setSizePolicy(sizePolicy)
        self.icon_1.setObjectName("icon_1")
        self.gridLayout.addWidget(self.icon_1, 3, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 0, 12, 1, 1)
        self.time_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_7.sizePolicy().hasHeightForWidth())
        self.time_7.setSizePolicy(sizePolicy)
        self.time_7.setObjectName("time_7")
        self.gridLayout.addWidget(self.time_7, 0, 13, 1, 1)
        self.icon_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_5.sizePolicy().hasHeightForWidth())
        self.icon_5.setSizePolicy(sizePolicy)
        self.icon_5.setObjectName("icon_5")
        self.gridLayout.addWidget(self.icon_5, 3, 9, 1, 1)
        self.line_47 = QtWidgets.QFrame(self.centralwidget)
        self.line_47.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.gridLayout.addWidget(self.line_47, 2, 2, 1, 1)
        self.line_53 = QtWidgets.QFrame(self.centralwidget)
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.gridLayout.addWidget(self.line_53, 2, 14, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 0, 4, 1, 1)
        self.time_4_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_4_inf.sizePolicy().hasHeightForWidth())
        self.time_4_inf.setSizePolicy(sizePolicy)
        self.time_4_inf.setObjectName("time_4_inf")
        self.gridLayout.addWidget(self.time_4_inf, 2, 7, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 3, 6, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 0, 2, 1, 1)
        self.line_51 = QtWidgets.QFrame(self.centralwidget)
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.gridLayout.addWidget(self.line_51, 2, 10, 1, 1)
        self.line_41 = QtWidgets.QFrame(self.centralwidget)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.gridLayout.addWidget(self.line_41, 1, 5, 1, 1)
        self.time_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_1.sizePolicy().hasHeightForWidth())
        self.time_1.setSizePolicy(sizePolicy)
        self.time_1.setObjectName("time_1")
        self.gridLayout.addWidget(self.time_1, 0, 1, 1, 1)
        self.line_45 = QtWidgets.QFrame(self.centralwidget)
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.gridLayout.addWidget(self.line_45, 1, 13, 1, 1)
        self.time_5_inf = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_5_inf.sizePolicy().hasHeightForWidth())
        self.time_5_inf.setSizePolicy(sizePolicy)
        self.time_5_inf.setObjectName("time_5_inf")
        self.gridLayout.addWidget(self.time_5_inf, 2, 9, 1, 1)
        self.icon_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_7.sizePolicy().hasHeightForWidth())
        self.icon_7.setSizePolicy(sizePolicy)
        self.icon_7.setObjectName("icon_7")
        self.gridLayout.addWidget(self.icon_7, 3, 13, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.listInfo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listInfo.sizePolicy().hasHeightForWidth())
        self.listInfo.setSizePolicy(sizePolicy)
        self.listInfo.setStyleSheet("font: 36pt \"Cantarell\";")
        self.listInfo.setObjectName("listInfo")
        self.horizontalLayout_5.addWidget(self.listInfo)
        self.iconToday = QtWidgets.QLabel(self.centralwidget)
        self.iconToday.setObjectName("iconToday")
        self.horizontalLayout_5.addWidget(self.iconToday)
        self.listCelsius = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listCelsius.sizePolicy().hasHeightForWidth())
        self.listCelsius.setSizePolicy(sizePolicy)
        self.listCelsius.setStyleSheet("font: 36pt \"Cantarell\";")
        self.listCelsius.setObjectName("listCelsius")
        self.horizontalLayout_5.addWidget(self.listCelsius)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listDay_1 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_1.setObjectName("listDay_1")
        self.horizontalLayout_2.addWidget(self.listDay_1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.listDay_2 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_2.setObjectName("listDay_2")
        self.horizontalLayout_2.addWidget(self.listDay_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.listDay_3 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_3.setObjectName("listDay_3")
        self.horizontalLayout_2.addWidget(self.listDay_3)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.listDay_4 = QtWidgets.QLabel(self.centralwidget)
        self.listDay_4.setObjectName("listDay_4")
        self.horizontalLayout_2.addWidget(self.listDay_4)
        self.gridLayout_6.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineSearch, self.pushSearch)
        MainWindow.setTabOrder(self.pushSearch, self.pushRefresh)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textMain.setText(_translate("MainWindow",
                                         "<html><head/><body><p><span style=\" font-size:36pt;\">ArchWeather</span></p></body></html>"))
        self.listCity.setText(_translate("MainWindow",
                                         "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">dfghh</span></p></body></html>"))
        self.pushSearch.setText(_translate("MainWindow", "Найти"))
        self.pushSearch.setShortcut(_translate("MainWindow", "Return"))
        self.pushRefresh.setText(_translate("MainWindow", "Обновить"))
        self.time_6_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_6_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_7_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_7_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_4.setText(_translate("MainWindow", "TextLabel"))
        self.icon_3.setText(_translate("MainWindow", "TextLabel"))
        self.time_2_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_2_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_3_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_3_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_4.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_4.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_5.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_5.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_6.setText(_translate("MainWindow", "TextLabel"))
        self.icon_2.setText(_translate("MainWindow", "TextLabel"))
        self.time_8_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_8_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_3.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_3.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_8.setText(_translate("MainWindow", "TextLabel"))
        self.time_2.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_2.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_6.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_6.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_8.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_8.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_1_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_1_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_1.setText(_translate("MainWindow", "TextLabel"))
        self.time_7.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_7.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_5.setText(_translate("MainWindow", "TextLabel"))
        self.time_4_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_4_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_1.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_1.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.time_5_inf.setToolTip(
            _translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.time_5_inf.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.icon_7.setText(_translate("MainWindow", "TextLabel"))
        self.listInfo.setText(
            _translate("MainWindow", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.iconToday.setText(_translate("MainWindow", "TextLabel"))
        self.listCelsius.setText(_translate("MainWindow", "<html><head/><body><p>TextLabel</p></body></html>"))
        self.listDay_1.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_2.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_3.setText(_translate("MainWindow", "TextLabel"))
        self.listDay_4.setText(_translate("MainWindow", "TextLabel"))
